version: '3'
services:
  node:
    image: "node:9"
    user: "node"
    working_dir: "/home/node"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "node index.js"
